config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'documents#index'
  devise_for :users

  resources :documents, only: %i[index show create new]
  get '/index', to: "index#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_many_attached :files
  validates :files, presence: true
  validates :file_name, presence: true, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET all documents
  def index
    @documents = Document.all
    render "index"
  end

  # GET single file
  def show
    @document = Document.find(params[:id])
    render "view_document"
  end

  # POST a document
  def create
    document = Document.new(document_params)
    document.user = current_user
    if document.valid?
      document.save!
      flash[:success] = ["Upload was successful"]
      redirect_to documents_path
    else
      flash[:error] = document.errors.full_messages()
      redirect_to new_document_path
    end
  end

  def new
    @document = Document.new
    render "new_document"
  end

  private

  def document_params
    params.require(:document).permit(:file_name, files: [])
  end
end

app/controllers/index_controller.rb
# frozen_string_literal: true

class IndexController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/index_helper.rb
# frozen_string_literal: true

module IndexHelper
end

app/views/documents/index.html.erb
<h1 class="topic">List of all files</h1>

<table>
  <thead>
  <tr>
    <th>Doc ID </th>
    <th>File Name </th>
    <th>File </th>
    <th>Total </th>
  </tr>
  </thead>
  <tbody>

  <% @documents.each do |document| %>
    <tr>
      <td><%= document.id%></td>
      <td><%= document.file_name%></td>
      <td>
        <%document.files.each do |file| %>
          <li><%= file.filename %></li>
        <% end %>
      </td>
      <td><%= document.files.count%></td>
      <td><%= link_to "View file", document_path(document) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/documents/new_document.html.erb
<div>
  <h2>Upload your documents here</h2>

  <%= form_for @document, html: {class: 'form'} do |f| %>
    <div class="field">
      <%= f.label :file_name %>
      <%= f.text_field :file_name, required: true %>
    </div>
    <div class="field">
      <%= f.label :files %>
      <%= f.file_field :files, required: true, multiple: true, direct_upload: true %>
    </div>
    <%= f.submit "Upload"%>
  <% end%>
</div>

app/views/documents/view_document.html.erb
<p id="notice"><%= notice %></p>

<div>
  <div>
    <% @document.files.each do |file| %>
      <li>
        <h3><%= file.filename %></h3>
        <%= link_to "Click to preview", rails_blob_path(file, disposition: "preview"), target: :blank, :class => "title-link" %>
        <%= link_to "Click to download", rails_blob_path(file, disposition: "attachment"), :class => "title-link" %>
      </li>
    <% end %>
  </div>
</div>

<%= link_to 'Go back', documents_path, :class => "back-btn" %>

app/views/index/index.html.erb
<h1>File Transfer App</h1>
<p>Welcome: This is a File Transfer App</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileTransferApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
  <div class="header-topics">
    <%= link_to "All Files", documents_path, :class => "title-link" %>
    <%= link_to "Upload Files", new_document_path, :class => "title-link" %>
  </div>
</header>

<% flash.each do |message_type, messages| %>
  <div class="alert alert-<%= message_type %>">
    <% if messages.instance_of?(String) %>
      <%= messages %>
    <% elsif messages.instance_of? Array%>
      <% messages.each do |message| %>
        <li><%= message%></li>
      <% end %>

    <% end %>
  </div>
<% end %>

<%= yield %>
</body>
</html>